/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 7.0.4 */
public interface GrammarTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTSTATEMENT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTEXPRESSION1 = 8;
  public int JJTEXPRESSION2 = 9;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "Expression",
    "Expression1",
    "Expression2",
  };
}
/* JavaCC - OriginalChecksum=03a0f0d96e7c8cc3262e5281520d4b0c (do not edit this line) */
